apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e31nitoel-java-springboot
  janus-idp.io/tekton: e31nitoel-java-springboot
  backstage.io/kubernetes-id: e31nitoel-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e31nitoel-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
